name: guzo_go_demo
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.1.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  #  flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker:
    git:
      url: https://github.com/HasanAlqaisi/flutter_datetime_picker.git
  flutter_easyloading: ^3.0.5
  
  get: ^4.6.5
  get_it: ^7.2.0
  get_storage: ^2.0.3
 
  google_fonts: ^4.0.4
  image_picker: ^0.8.6
  intl: ^0.17.0
  logger: ^1.1.0
  overlay_support: ^2.1.0
  
dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  json_serializable: ">4.4.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  # image_path_ios: "assets/images/HROTG_icon4.png"
  # image_path: "assets/icons/Schindler_app_icon.png"
  # # image_path: "assets/images/HROTG_icon2.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "assets/images/red_back.png"
  # adaptive_icon_foreground: "assets/images/HROTG_text500.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
 
        #  style: italic
    - family: MS_JHBD
      fonts:
        - asset: fonts/ms_jhbd/msjhbd.ttf
